# Generated by Django 3.1.4 on 2021-07-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha',
            field=models.CharField(default='0/0/0', max_length=50),
            preserve_default=False,
        ),
    ]
